### ISSUE TITLE
Add final LOC items and corresponding metadata

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#74] opened 2021-04-09 13:31 UTC

**Comment by CourtneyMcClellan** [comment] 2021-04-23 12:10
Upload files in here (leave out anything in the folders)

https://drive.google.com/drive/folders/1D3eC-cbe34NUtfy9SV-h5LdR3adtJ7wW?usp=sharing

**Comment by CourtneyMcClellan** [comment] 2021-04-23 12:28
Remove the current items in the collection

**Comment by jaimemears** [comment] 2021-04-23 14:10
@CourtneyMcClellan when the files all have id names and links can you assign this to @adamjarling to upload?

**Comment by CourtneyMcClellan** [comment] 2021-04-23 17:54
We are working with curators, this will likely take a couple of passes. Please don't close out this ticket after this initial upload.

**Comment by adamjarling** [comment] 2021-04-24 12:18
@jaimemears Do we want to work from the same metadata spreadsheet you previously created?  I think we were pulling Questions, and also Work descriptions from your original metadata spreadsheet.

**Comment by CourtneyMcClellan** [comment] 2021-04-24 13:03
Yes, add to this metadata, starting with row 9. Delete previous items. I

https://docs.google.com/spreadsheets/d/12Iq5AS0yb91KmpvMI-OwVpIn5__HQwH6eCjuH93imoY/edit#gid=0

**Comment by adamjarling** [comment] 2021-04-25 13:14
New Works are now added to the app.  Just as a reminder, the app uses local images, which are defined in this file:

```
src/services/loc-images.js
```

Then updated IIIF manifests, which supply Work's metadata, have been updated in the app's `public/iiif` folder. Each Work has it's own folder (representing a resolvable URI per IIIF spec). Eventually these would likely live in a IIIF server environment somewhere.

![image](https://user-images.githubusercontent.com/3020266/115994738-d233f100-a59d-11eb-8fff-de857506f6d3.png)

![image](https://user-images.githubusercontent.com/3020266/115994890-846bb880-a59e-11eb-97d0-61901ce4c178.png)

**Comment by adamjarling** [comment] 2021-04-25 13:20
@jaimemears @CourtneyMcClellan more clarification, the app still pulls whatever metadata is can from the LOC IIIF manifest.  There is additional metadata (such as Questions, curator annotations, etc.) which are specific to this application, and to update this info, you'd find the Work manifest in this file:

```
public/iiif/speculative-annotations-manifest.json
```

...and then just find where the information is stored.  Mostly it'll be under the `annotations` property for each Work manifest.

![image](https://user-images.githubusercontent.com/3020266/115995020-255a7380-a59f-11eb-91ba-561c93f92ea6.png)

**Comment by adamjarling** [comment] 2021-04-25 13:22
Moving this to the Needs feedback/action column, as the new Works need updated questions and descriptions.   We could use LOC manifest descriptions, but noticed a lot of them are either very short, or missing.

**Comment by adamjarling** [comment] 2021-04-25 13:49
@CourtneyMcClellan @jaimemears The following images don't seem to have LOC manifest files, so we can't display any metadata.   I haven't included them in the new batch up LOC images yet.   We could go one of 2 directions:

1. Display the images w/o metadata (this is the app default, just as protection for say that there's an error loading a LOC manifest for whatever reason).  Or,
2. We try to track down LOC IIIF manifest files for each, then plug them into the app.

![image](https://user-images.githubusercontent.com/3020266/115995926-e1696d80-a5a2-11eb-9fde-7e1ee3c2a89c.png)

**Comment by CourtneyMcClellan** [comment] 2021-04-25 14:21
Go ahead and display them without metadata, these are images that are free
to use but not on Loc.gov. Ultimately, we will have to write the metadata.
Thanks for checking!

**Comment by adamjarling** [comment] 2021-04-25 18:54
Got it.  Items added to the app.

**Comment by jaimemears** [comment] 2021-04-25 21:46
That’s correct. We are going to work with curators to get the language for these other fields and will update. Thank you!

**Comment by jaimemears** [comment] 2021-04-25 21:47
Hooray! Thank you!

**Comment by CourtneyMcClellan** [comment] 2021-04-28 13:06
@adamjarling Upload/replace additional 3 items here:https://drive.google.com/drive/folders/1kiiZuQHAlNnoPGyj_mVFnXZYkYmgg6Zm

**Comment by adamjarling** [comment] 2021-04-28 13:54
These are now replaced and pushed to staging.

**Comment by adamjarling** [comment] 2021-04-28 16:34
@jaimemears Looks like on the staging environment, we're getting CORS errors trying to grab the LOC manifest JSON file.  What this means is that the LOC server where these manifests are hosted has a policy on it to only deliver data to requests coming from LOC domains.  It's blocking the request coming from our staging server domain ( https://nervous-gates-006218.netlify.app/ )  Wondering if you could run this by your devs and get their thoughts?   

This also likely would go away once we move the app to LOC hosting....

![image](https://user-images.githubusercontent.com/3020266/116439496-3ca29680-a815-11eb-8408-b63271a6a05a.png)

**Comment by jaimemears** [comment] 2021-04-28 19:10
Gotcha. Ok I will follow up on this.

**Comment by jaimemears** [comment] 2021-05-03 16:56
@adamjarling  CORS headers errors are possibly because the page had a higher level error, eg a 500 error. Recommendation from Lc staff is to code to deal with the possibility of a 500 response and catch, retry, and notify the user etc. When 500 error was reproduced it was fixed with a refresh. LC staff looking into origin of error.

**Comment by CourtneyMcClellan** [comment] 2021-05-04 18:51
@adamjarling We have another round of items to be uploaded, can be found here: https://drive.google.com/drive/folders/1Dkmhr2e_REikfFC9LCxXgAze1lb4CBDN?usp=sharing

These items already have a thumbnail as well.

**Comment by adamjarling** [comment] 2021-05-09 13:20
Updating the new items now (this takes a while).  Some of the items aren't resolving with IIIF Manifest URLs on LOC's end, so could someone at some point update this file?   

https://docs.google.com/spreadsheets/d/12Iq5AS0yb91KmpvMI-OwVpIn5__HQwH6eCjuH93imoY/edit#gid=0

**Comment by adamjarling** [comment] 2021-05-09 14:26
Latest images uploaded.  

Pushing this issue back to "Needs Feedback" column until all images are finalized.

**Comment by CourtneyMcClellan** [comment] 2021-05-13 18:14
Delete Item 34 (exists as and as master-pnp-ppmsca-02900-02935u_thumbnail in thumbnail). I have noted this in the thumbnail issue as well. 

2 new items to add:
https://drive.google.com/drive/folders/1IULtK9x9l2r1bOP3QlGVg5xPoIt--P5O?usp=sharing

**Comment by CourtneyMcClellan** [comment] 2021-05-21 20:21
Next Round of item updates: 
https://drive.google.com/drive/folders/1IULtK9x9l2r1bOP3QlGVg5xPoIt--P5O?usp=sharing

have the Barton item (service-pnp-ppmsca-02900-02935v.jpg) match with the Barton thumbnail (right now the Barton item open to an already included Maya Lin)
add the Mitchell (03012768.jpg)
add declaration of women's rights (mss11049028.tif)
update higher res Maya Lin (master-pnp-ppmsca-09500-09504u.tif)
update vaccine video still (mbrs00056792.tif)
Remove Blackmun (mm2099084430.jpg)

Thumbnails for these items all exist in the thumbnail folder here: https://drive.google.com/drive/folders/18HCarxf-18YbQHUvKuGKF69l5kjbft3c?usp=sharing

**Comment by adamjarling** [comment] 2021-05-23 19:25
Ok, these should all be updated.  It looks like the `master-pnp-ppmsca-09500-09504u.tif` is a duplicate of `97505164`, so I'm just using `97505164`.  Let me know if this is not correct?

**Comment by CourtneyMcClellan** [comment] 2021-05-23 19:39
We were uploading it as master-pnp-ppmsca-09500-09504u because the other
file is too small. I know it may take a while to upload, but in the
previous version we could not read the text.

**Comment by adamjarling** [comment] 2021-05-27 13:26
This was updated...so either @CourtneyMcClellan or @jaimemears  let me know if this looks done or more needed here?

**Comment by CourtneyMcClellan** [comment] 2021-05-27 14:03
add last item: https://drive.google.com/drive/folders/1ccrDSXXzsCtaXY4q2XvdXLl4Nbu48XnO?usp=sharing

associated thumbnail in thumbnail folder: https://drive.google.com/drive/folders/18HCarxf-18YbQHUvKuGKF69l5kjbft3c?usp=sharing

**Comment by adamjarling** [comment] 2021-05-27 21:23
@CourtneyMcClellan @jaimemears I'm creating this now, however the `id` `ms014094` isn't resolving, FYI.   @jaimemears  you could add this to your list of items to verify tomorrow perhaps?

https://www.loc.gov/item/ms014094/manifest.json

**Comment by adamjarling** [comment] 2021-05-27 21:42
![image](https://user-images.githubusercontent.com/3020266/119900682-76e17f80-bf0a-11eb-88e8-8f57b3d55b78.png)

**Comment by jaimemears** [comment] 2021-06-03 17:06
@CourtneyMcClellan can you QA this list and if its all good close the ticket?

Muybridge- Collection says generic
March on Washington: Stray ( in subject column
Candide- can’t link out to individual item on loc.gov
Lincoln- research link opens to wrong topic
Millhous-- the subject heading is very long and includes many thinks that don’t seem relevant to the topic, is there anything that can be done about this?
Warren Brown v Board long subject headings that don’t all seem relevant, has spot for questions--says generic
Pueblo- generic collection placeholder, does not open to blueprint in find on loc.gov
Statue of Liberty- does not open to blueprint item in find on loc.gov
Copeland- no created date
Barton- has spot for questions rather than research, placeholder collection
Rhone- research opens to wrong materials (federal theater again), item with restricted access
Newspaper- opens to wrong research (federal theater again)
Maria Mitchell- placeholder collection
Declaration of Women’s Rights placeholder collection

**Closed as completed** 2021-06-07 19:24 UTC
Labels: MVP
