### ISSUE TITLE
Image gallery should be numbered

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#91] opened 2021-04-16 17:57 UTC
Images in gallery should be numbered. number should exist center-aligned underneath each thumbnail.

Jessica - could you mock up colors and fonts for this?

**Comment by jessvu** [comment] 2021-04-20 01:09
![image](https://user-images.githubusercontent.com/32075716/115322517-44e33d80-a154-11eb-98d6-d96935cda0b6.png)
Mockups are up in figma

**Comment by adamjarling** [comment] 2021-04-23 13:09
First step on this I'm pushing up now.  Still need to figure out how the pagination controls can work to be numbers, but the main functionality of showing images in a carousel, vertically centered should be in place.

![image](https://user-images.githubusercontent.com/3020266/115875811-3e322000-a40b-11eb-83d1-725ebfcc269e.png)

**Comment by adamjarling** [comment] 2021-04-25 13:27
@CourtneyMcClellan  In the interest of time, I'm curious if we're ok with closing this issue as is?  It's using the carousel package's default styling/functionality for arrows and pagination.   And I think the core functionality of the issue is addressed in this ticket, as we totally upgraded how selecting a new image is handled in the UI.

If updating the navigation arrow style and customizing bottom pagination is still desired, could we create a new issue, tightly scoped just to those enhancements?

**Comment by CourtneyMcClellan** [comment] 2021-04-25 13:30
Sounds good!

**Comment by adamjarling** [comment] 2021-04-25 14:13
Related clean up issue:  https://github.com/adamjarling/loc-speculative-annotations/issues/96

**Closed as completed** 2021-04-25 14:12 UTC
